<x-layouts.app title="Configuración del CRM">
<div class="crm-page"><section class="crm-hero"><p class="crm-eyebrow">CRM de inversiones</p><h2 class="crm-title">Configuración del CRM</h2><p class="mt-2 text-blue-100">Personaliza los textos que verán tus prospectos y asesores.</p>@if($previewAdvisor)<a class="crm-button crm-button--secondary mt-5" href="{{ route('investments.advisors.public',$previewAdvisor->public_token) }}" target="_blank" rel="noopener noreferrer">Ver formulario público</a>@endif</section>
@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('status') }}</div>@endif
<form class="mt-5 grid gap-5" method="post" action="{{ route('investments.crm.settings.update') }}">@csrf @method('put')
@php($groups=['Formulario de captación'=>['public_form_brand'=>'Marca','public_form_subtitle'=>'Subtítulo de marca','public_form_title'=>'Título','public_form_description'=>'Descripción','public_form_name_label'=>'Etiqueta nombre','public_form_name_placeholder'=>'Placeholder nombre','public_form_phone_label'=>'Etiqueta celular','public_form_phone_placeholder'=>'Placeholder celular','public_form_shares_label'=>'Etiqueta acciones','public_form_shares_placeholder'=>'Placeholder acciones','public_form_shares_help'=>'Ayuda acciones','public_form_contact_question'=>'Pregunta de contacto','public_form_whatsapp_label'=>'Opción WhatsApp','public_form_call_label'=>'Opción llamada','public_form_consent_text'=>'Consentimiento','public_form_submit_text'=>'Texto del botón'],'Calificación de atención'=>['service_rating_question'=>'Pregunta','service_rating_optional_text'=>'Texto opcional','service_rating_poor_label'=>'Mala','service_rating_regular_label'=>'Regular','service_rating_good_label'=>'Buena','service_rating_very_good_label'=>'Muy buena'],'Registro exitoso'=>['success_title'=>'Título','success_message'=>'Mensaje','success_contact_message'=>'Mensaje de contacto','success_code_label'=>'Etiqueta del código'],'Portal del asesor'=>['advisor_portal_title'=>'Título del portal','advisor_portal_subtitle'=>'Subtítulo del portal','advisor_dashboard_greeting'=>'Saludo','advisor_dashboard_description'=>'Descripción del panel','login_title'=>'Título del acceso','login_subtitle'=>'Subtítulo del acceso','login_code_label'=>'Etiqueta del código','login_pin_label'=>'Etiqueta PIN','login_button_text'=>'Texto del botón','footer_text'=>'Texto del pie']])
@foreach($groups as $heading=>$fields)<section class="crm-card"><h3 class="crm-section-title">{{ $heading }}</h3><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach($fields as $field=>$label)@php($long=str_contains($field,'description')||str_contains($field,'message')||str_contains($field,'consent')||$field==='footer_text')<div @class(['md:col-span-2'=>$long])><label class="crm-label" for="{{ $field }}">{{ $label }}</label>@if($long)<textarea class="crm-form-input" id="{{ $field }}" name="{{ $field }}" rows="3">{{ old($field,$settings[$field]) }}</textarea>@else<input class="crm-form-input" id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$settings[$field]) }}">@endif @error($field)<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach</div></section>@endforeach
<button class="crm-button crm-button--primary justify-self-start" type="submit">Guardar cambios</button></form>
<form class="mt-3" method="post" action="{{ route('investments.crm.settings.restore') }}" data-confirm-title="Restaurar textos" data-confirm-message="¿Deseas restaurar los textos predeterminados del CRM?">@csrf<button class="crm-button crm-button--secondary" type="submit">Restaurar predeterminados</button></form></div>
</x-layouts.app>
