<?php
namespace Tests\Feature;
use App\Models\InvestmentAdvisor; use App\Models\InvestmentProspect; use App\Models\Investor; use App\Models\Person; use App\Models\User;
use App\Services\InvestmentProspectAssignmentService; use App\Services\InvestmentProspectInteractionService; use App\Services\InvestmentProspectService; use App\Services\InvestmentProspectWorkflowService;
use Carbon\Carbon; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException; use Tests\TestCase;
class InvestmentCrmTest extends TestCase
{
 use RefreshDatabase;
 public function test_timezone_is_isolated_and_workflow_records_controlled_history(): void { $this->assertSame('UTC',config('app.timezone')); $this->assertSame('America/La_Paz',config('investment_crm.timezone')); [$admin,$advisor,$p]=$this->fixture(); $s=app(InvestmentProspectWorkflowService::class); $s->changeStatus($p,$admin,'in_transition',null); $s->changeStatus($p->refresh(),$admin,'closed',null); $this->assertSame('closed',$p->refresh()->status); $this->assertSame(3,$p->statusHistory()->count()); $this->assertDatabaseHas('audit_logs',['action'=>'investment_prospect_status_changed','auditable_id'=>$p->id]); $p2=$this->prospect($advisor,'70000002'); $this->expectException(ValidationException::class); $s->changeStatus($p2,$admin,'closed',null); }
 public function test_advisor_scope_interaction_timezone_and_no_financial_entities(): void { [$admin,$a,$p,$advisorUser]=$this->fixture(true); $b=$this->advisor('ASE-0002'); $other=$this->prospect($b,'70000003'); $this->actingAs($advisorUser)->get(route('investments.prospects.index'))->assertOk()->assertSee($p->prospect_number)->assertDontSee($other->prospect_number); $this->get(route('investments.prospects.show',$other))->assertForbidden(); Carbon::setTestNow('2026-09-08 15:00:00'); app(InvestmentProspectInteractionService::class)->createInteraction($p,$advisorUser,['type'=>'whatsapp','channel'=>'whatsapp','notes'=>'Información solicitada','occurred_at'=>'2026-09-08T10:00','next_follow_up_at'=>'2026-09-09T10:00']); $i=$p->interactions()->first(); $this->assertSame('2026-09-08 14:00:00',$i->occurred_at->format('Y-m-d H:i:s')); $this->assertSame('2026-09-09 14:00:00',$i->next_follow_up_at->format('Y-m-d H:i:s')); $this->assertSame(0,Person::count()); $this->assertSame(0,Investor::count()); }
 public function test_reassignment_preserves_original_and_changes_advisor_visibility(): void { [$admin,$a,$p,$userA]=$this->fixture(true); $userB=$this->user('asesor_inversiones','b@test.local'); $b=$this->advisor('ASE-0002',$userB); app(InvestmentProspectAssignmentService::class)->reassign($p,$b,$admin,'Distribución de cartera'); $this->assertSame($a->id,$p->refresh()->original_advisor_id); $this->assertSame($b->id,$p->current_advisor_id); $this->assertSame(2,$p->assignments()->count()); $this->actingAs($userA)->get(route('investments.prospects.show',$p))->assertForbidden(); $this->actingAs($userB)->get(route('investments.prospects.show',$p))->assertOk(); }
 public function test_kanban_requires_authentication_and_displays_each_real_status(): void { [$admin,$advisor,$captured]=$this->fixture(); foreach(['in_transition','closed','lost'] as $index=>$status){ $prospect=$this->prospect($advisor,'7000001'.($index+2)); $prospect->update(['status'=>$status]); } $this->get(route('investments.crm.kanban'))->assertRedirect(); $this->actingAs($admin)->get(route('investments.crm.kanban'))->assertOk()->assertSee('CAPTADO')->assertSee('EN TRANSICIÓN')->assertSee('CERRADO')->assertSee('PERDIDO')->assertSee($captured->prospect_number); }
 public function test_lost_requires_reason_and_advisor_cannot_reassign(): void { [$admin,$advisor,$prospect,$advisorUser]=$this->fixture(true); $this->actingAs($advisorUser)->patch(route('investments.prospects.status',$prospect),['status'=>'lost'])->assertSessionHasErrors('reason'); $this->assertSame('captured',$prospect->refresh()->status); $other=$this->advisor('ASE-0002'); $this->patch(route('investments.prospects.reassign',$prospect),['advisor_id'=>$other->id])->assertForbidden(); $this->actingAs($admin)->patch(route('investments.prospects.reassign',$prospect),['advisor_id'=>$other->id,'reason'=>'Cobertura'])->assertRedirect(); $this->assertSame($other->id,$prospect->refresh()->current_advisor_id); }
 public function test_all_initial_interaction_types_are_supported_without_creating_other_domains(): void { [$admin,$advisor,$prospect]=$this->fixture(); Carbon::setTestNow('2026-09-08 18:00:00'); foreach(['call','whatsapp','meeting','note'] as $type){ app(InvestmentProspectInteractionService::class)->createInteraction($prospect->refresh(),$admin,['type'=>$type,'channel'=>'internal','occurred_at'=>'2026-09-08T10:00']); } $this->assertEqualsCanonicalizing(['call','meeting','note','whatsapp'],$prospect->interactions()->pluck('type')->all()); $this->assertSame(4,$prospect->interactions()->count()); $this->assertSame(0,Person::count()); $this->assertSame(0,Investor::count()); }
 public function test_follow_up_filters_use_crm_timezone_boundaries(): void { [$admin,$advisor,$today]=$this->fixture(); Carbon::setTestNow('2026-09-08 12:00:00'); $today->update(['next_follow_up_at'=>'2026-09-08 04:30:00','last_interaction_at'=>'2026-09-08 04:30:00']); $overdue=$this->prospect($advisor,'70000022'); $overdue->update(['next_follow_up_at'=>'2026-09-07 10:00:00']); $none=$this->prospect($advisor,'70000023'); $this->actingAs($admin)->get(route('investments.prospects.index',['follow_up'=>'today','interaction_from'=>'2026-09-08','interaction_to'=>'2026-09-08']))->assertOk()->assertSee($today->prospect_number)->assertDontSee($overdue->prospect_number)->assertDontSee($none->prospect_number); }
 private function fixture(bool $linked=false): array { $admin=$this->user('superadministrador','admin@test.local'); $u=$linked?$this->user('asesor_inversiones','a@test.local'):null; $a=$this->advisor('ASE-0001',$u); $p=$this->prospect($a,'70000001'); return [$admin,$a,$p,$u]; }
 private function prospect($a,$phone){ return app(InvestmentProspectService::class)->createFromAdvisorQr($a,['full_name'=>'Prospecto','phone'=>$phone,'requested_shares'=>10,'preferred_contact_method'=>'whatsapp'],'127.0.0.1','Test')['prospect']; }
 private function advisor($n,$u=null){ return InvestmentAdvisor::create(['advisor_number'=>$n,'public_id'=>(string)Str::uuid(),'public_token'=>Str::random(64),'full_name'=>$n,'phone'=>'71111111','user_id'=>$u?->id,'is_active'=>true]); }
 private function user($role,$email){ return User::create(['name'=>$role,'email'=>$email,'role'=>$role,'user_type'=>'internal','is_active'=>true,'password'=>Hash::make('secret')]); }
}
