<?php

$permissions = [
    'dashboard.view',
    'users.view', 'users.create', 'users.update', 'users.block', 'users.activate',
    'users.reset-password', 'users.delete', 'users.restore', 'users.assign-role',
    'affiliates.view', 'affiliates.create', 'affiliates.update', 'affiliates.update_personal',
    'affiliates.update_institutional', 'affiliates.change_sector', 'affiliates.change_plan',
    'affiliates.change_status', 'affiliates.manage_photo', 'affiliates.manage_access',
    'affiliates.manage_credential', 'affiliates.view_timeline', 'affiliates.view_audit',
    'affiliates.soft_delete', 'affiliates.approve', 'affiliates.reject', 'affiliates.delete',
    'affiliates.restore', 'affiliates.reset-password',
    'affiliate_access.view', 'affiliate_access.block', 'affiliate_access.activate',
    'affiliate_access.reset_password', 'affiliate_access.revoke_sessions',
    'affiliate_access.change_email',
    'payments.view', 'payments.create', 'payments.update', 'payments.update_pending',
    'payments.verify', 'payments.confirm', 'payments.reject', 'payments.void',
    'cash_deposits.view_own', 'cash_deposits.create', 'cash_deposits.view_all',
    'cash_deposits.confirm', 'cash_deposits.reject',
    'payments.cancel', 'payments.receipt', 'payments.view_receipt', 'payments.download_receipt',
    'credentials.view', 'credentials.download', 'credentials.print',
    'settings.view', 'settings.update', 'reports.view', 'reports.export',
    'roles.view', 'roles.update', 'audit.view', 'audit.export',
    'credits.view', 'credits.create', 'credits.update', 'credits.approve',
    'investors.view', 'investors.create', 'investors.update',
    'investment_advisors.view', 'investment_advisors.create', 'investment_advisors.update',
    'investment_prospects.view', 'investment_prospects.create', 'investment_prospects.update',
    'investment_prospects.reassign', 'investment_prospect_interactions.view', 'investment_prospect_interactions.create',
    'investment_crm_settings.view', 'investment_crm_settings.update',
    'store.view', 'store.manage-products', 'store.manage-settings', 'store.manage-shipping',
    'store.manage-coupons', 'store.manage-orders', 'store.verify-receipts',
];

return [
    'permissions' => $permissions,
    'labels' => [
        'superadministrador' => 'Super Administrador',
        'gerente' => 'Gerente',
        'secretaria' => 'Secretaría',
        'cajero' => 'Cajero',
        'caja' => 'Caja',
        'administrador' => 'Administrador (legado)',
        'administrador_sector' => 'Administrador de sector',
        'consulta' => 'Consulta',
        'asesor_inversiones' => 'Asesor de Inversiones',
    ],
    'assignable' => ['superadministrador', 'gerente', 'secretaria', 'cajero', 'caja', 'asesor_inversiones'],
    'descriptions' => [
        'caja' => 'Gestión operativa de cobros, pagos y consulta financiera autorizada.',
    ],
    'roles' => [
        'superadministrador' => $permissions,
        'administrador' => $permissions,
        'gerente' => [
            'dashboard.view', 'users.view', 'affiliates.view', 'payments.view', 'credentials.view',
            'settings.view', 'reports.view', 'reports.export', 'audit.view', 'roles.view',
            'affiliates.update_institutional', 'affiliates.change_sector', 'affiliates.change_plan',
            'affiliates.change_status', 'affiliates.view_timeline', 'affiliates.view_audit',
            'affiliates.manage_credential',
            'payments.confirm', 'payments.reject', 'payments.view_receipt',
            'cash_deposits.view_all', 'cash_deposits.confirm', 'cash_deposits.reject',
            'affiliate_access.view',
            'credits.view', 'investors.view', 'store.view',
            'investment_advisors.view',
            'investment_prospects.view',
            'investment_prospects.update', 'investment_prospects.reassign',
            'investment_prospect_interactions.view', 'investment_prospect_interactions.create',
            'investment_crm_settings.view',
        ],
        'secretaria' => [
            'dashboard.view', 'users.view', 'affiliates.view', 'affiliates.create', 'affiliates.update',
            'affiliates.update_personal', 'affiliates.update_institutional', 'affiliates.change_sector',
            'affiliates.change_plan', 'affiliates.manage_photo', 'affiliates.manage_access',
            'affiliates.view_timeline',
            'affiliates.approve', 'affiliates.reject', 'affiliates.reset-password',
            'affiliate_access.view', 'affiliate_access.block', 'affiliate_access.activate',
            'affiliate_access.reset_password', 'affiliate_access.revoke_sessions',
            'affiliate_access.change_email',
            'payments.view', 'payments.create', 'payments.update', 'payments.update_pending',
            'payments.confirm', 'payments.reject', 'payments.receipt', 'payments.view_receipt',
            'payments.download_receipt',
            'credentials.view', 'credentials.download', 'credentials.print',
            'reports.view', 'settings.view', 'store.view', 'store.manage-products', 'store.manage-shipping', 'store.manage-coupons', 'store.verify-receipts',
        ],
        'cajero' => [
            'dashboard.view', 'affiliates.view', 'payments.view', 'payments.create', 'payments.update',
            'payments.update_pending', 'payments.verify', 'payments.receipt',
            'cash_deposits.view_own', 'cash_deposits.create',
            'payments.view_receipt', 'payments.download_receipt', 'credits.view',
        ],
        'caja' => [
            'dashboard.view', 'affiliates.view', 'payments.view', 'payments.create', 'payments.update',
            'payments.update_pending', 'payments.verify', 'payments.receipt',
            'cash_deposits.view_own', 'cash_deposits.create',
            'payments.view_receipt', 'payments.download_receipt', 'credits.view', 'investors.view',
        ],
        'administrador_sector' => [
            'dashboard.view', 'affiliates.view', 'affiliates.create', 'affiliates.update',
            'payments.view', 'credentials.view', 'credentials.download',
            'credentials.print', 'reports.view',
        ],
        'consulta' => ['dashboard.view', 'affiliates.view', 'payments.view', 'reports.view', 'credits.view', 'store.view'],
        'asesor_inversiones' => ['investment_prospects.view', 'investment_prospects.update', 'investment_prospect_interactions.view', 'investment_prospect_interactions.create'],
    ],
];
