<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $settings['public_form_title'] }} - {{ $settings['public_form_brand'] }}</title>@vite(['resources/css/app.css','resources/css/crm.css'])</head>
<body class="crm-public"><main class="crm-public-shell"><header class="crm-public-header"><p class="text-2xl font-black">{{ $settings['public_form_brand'] }}</p><p class="crm-eyebrow">{{ $settings['public_form_subtitle'] }}</p><div class="mt-5 flex items-center gap-3"><span class="crm-avatar">@if($advisor->photoUrl())<img src="{{ $advisor->photoUrl() }}" alt="Fotografía de {{ $advisor->full_name }}">@else{{ collect(preg_split('/\s+/',trim($advisor->full_name)))->filter()->take(2)->map(fn($part)=>mb_substr($part,0,1))->join('') }}@endif</span><div><p class="text-xs font-bold uppercase text-blue-100">Asesor de inversiones</p><p class="font-black">{{ $advisor->full_name }}</p><p class="text-sm text-[#f5c940]">{{ $advisor->advisor_number }}</p></div></div></header>
<section class="crm-public-form">
@if(($result['status']??null)==='created')<div class="py-4 text-center"><span class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-3xl font-black text-emerald-700">✓</span><h1 class="crm-title mt-5">{{ $settings['success_title'] }}</h1><p class="crm-muted mt-3">{{ $settings['success_message'] }}</p><p class="mt-2 font-bold">{{ $settings['success_contact_message'] }}</p><p class="crm-muted mt-6 text-sm">{{ $settings['success_code_label'] }}</p><p class="mt-1 rounded-xl bg-blue-50 px-4 py-3 text-xl font-black">{{ $result['prospect_number'] }}</p></div>
@elseif(($result['status']??null)==='existing')<div class="py-4 text-center"><h1 class="crm-title">Registro encontrado</h1><p class="crm-muted mt-3">Ya existe un registro asociado a este número.</p><p class="mt-2 font-bold">{{ $settings['success_contact_message'] }}</p></div>
@else<header class="text-center"><h1 class="crm-title">{{ $settings['public_form_title'] }}</h1><p class="crm-muted mt-3">{{ $settings['public_form_description'] }}</p></header><form class="mt-7 grid gap-4" method="post">@csrf
<div><label class="crm-label" for="full_name">{{ $settings['public_form_name_label'] }}</label><input class="crm-form-input" id="full_name" name="full_name" value="{{ old('full_name') }}" placeholder="{{ $settings['public_form_name_placeholder'] }}" required maxlength="255" autocomplete="name">@error('full_name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="crm-label" for="phone">{{ $settings['public_form_phone_label'] }}</label><input class="crm-form-input" id="phone" name="phone" value="{{ old('phone') }}" placeholder="{{ $settings['public_form_phone_placeholder'] }}" required maxlength="40" inputmode="tel" autocomplete="tel">@error('phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="crm-label" for="requested_shares">{{ $settings['public_form_shares_label'] }}</label><input class="crm-form-input" type="number" id="requested_shares" name="requested_shares" value="{{ old('requested_shares') }}" placeholder="{{ $settings['public_form_shares_placeholder'] }}" required min="1"><p class="crm-muted mt-1 text-xs">{{ $settings['public_form_shares_help'] }}</p>@error('requested_shares')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<fieldset><legend class="crm-label">{{ $settings['public_form_contact_question'] }}</legend><div class="crm-contact-options"><label class="crm-contact-option"><input type="radio" name="preferred_contact_method" value="whatsapp" @checked(old('preferred_contact_method','whatsapp')==='whatsapp')> {{ $settings['public_form_whatsapp_label'] }}</label><label class="crm-contact-option"><input type="radio" name="preferred_contact_method" value="call" @checked(old('preferred_contact_method')==='call')> {{ $settings['public_form_call_label'] }}</label></div></fieldset>
<label class="flex items-start gap-3 text-sm"><input class="mt-1 h-5 w-5" type="checkbox" checked disabled><span>{{ $settings['public_form_consent_text'] }}</span></label><fieldset><legend class="crm-label">{{ $settings['service_rating_question'] }} <span class="crm-muted font-normal">({{ $settings['service_rating_optional_text'] }})</span></legend><div class="crm-rating-options">@foreach(\App\Support\InvestmentProspectServiceRating::values() as $rating)<label class="crm-rating-option"><input type="radio" name="service_rating" value="{{ $rating }}" @checked(old('service_rating')===$rating)><span aria-hidden="true">{{ \App\Support\InvestmentProspectServiceRating::emoji($rating) }}</span><strong>{{ $settings['service_rating_'.$rating.'_label'] }}</strong></label>@endforeach</div>@error('service_rating')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</fieldset><button class="crm-button crm-button--primary w-full" type="submit">{{ $settings['public_form_submit_text'] }}</button></form>@endif
</section></main></body></html>
