<?php
namespace App\Http\Controllers\InvestmentCrm;
use App\Http\Controllers\Controller; use App\Models\InvestmentProspect; use App\Services\InvestmentAdvisorAuthService; use App\Services\InvestmentProspectInteractionService; use App\Services\InvestmentProspectWorkflowService; use App\Support\InvestmentProspectInteractionType; use App\Support\InvestmentProspectStatus; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class AdvisorProspectController extends Controller
{
 private function own(Request $r, InvestmentProspect $p){ $a=app(InvestmentAdvisorAuthService::class)->advisor($r); abort_unless($p->current_advisor_id===$a->id,404); return [$a,$p]; }
 public function show(Request $r, InvestmentProspect $prospect){ [$a,$p]=$this->own($r,$prospect); return view('investment-crm.advisor.show',['advisor'=>$a,'prospect'=>$p->load(['interactions'=>fn($q)=>$q->latest('occurred_at')]),'types'=>InvestmentProspectInteractionType::types(),'channels'=>InvestmentProspectInteractionType::channels()]); }
 public function interaction(Request $r, InvestmentProspect $prospect, InvestmentProspectInteractionService $s){ [$a]=$this->own($r,$prospect); $d=$r->validate(['type'=>['required',Rule::in(array_keys(InvestmentProspectInteractionType::types()))],'channel'=>['nullable',Rule::in(array_keys(InvestmentProspectInteractionType::channels()))],'notes'=>['nullable','string','max:3000'],'occurred_at'=>['nullable','date_format:Y-m-d\TH:i'],'next_follow_up_at'=>['nullable','date_format:Y-m-d\TH:i']]); $s->createInteractionForAdvisor($prospect,$a,$d); return back()->with('status','Interacción registrada.'); }
 public function status(Request $r, InvestmentProspect $prospect, InvestmentProspectWorkflowService $s){ [$a]=$this->own($r,$prospect); $d=$r->validate(['status'=>['required',Rule::in(InvestmentProspectStatus::values())],'reason'=>['nullable','string','max:1000']]); $updated=$s->changeStatusForAdvisor($prospect,$a,$d['status'],$d['reason']??null); if($r->expectsJson()) return response()->json(['ok'=>true,'status'=>$updated->status,'label'=>InvestmentProspectStatus::label($updated->status),'allowed_targets'=>$s->allowedTargetsForAdvisor($updated)]); return back()->with('status','Estado actualizado.'); }
}
